################################################################# 
# Dockerfile # # 
# Description: Select a "PASS" VCF from mutect2 

FROM ubuntu:16.04
MAINTAINER chunlei <chunlei.yu1990@gmail.com><xiaoyulei0406@163.com>


RUN apt-get -qq update && apt-get install -qqy \
    build-essential \
    lbzip2 \
#    openjdk-8-jdk \
    r-base-core \
    unzip \
    vim-common \
    wget \
    zlib1g-dev \
    libcurl4-openssl-dev \
    sudo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/


COPY ./hard_filerd.sh /opt/
